<?php
namespace Tests\Feature\Ozon;
use App\Enums\OzonProductStatus; use App\Models\Category; use App\Models\OzonAccount; use App\Models\OzonProduct; use App\Models\OzonWarehouse; use App\Models\Product; use App\Models\ProductAttribute; use App\Services\Ozon\OzonProductPreparationService; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Http; use Tests\TestCase;
class OzonPreparationServiceTest extends TestCase
{ use RefreshDatabase;
 protected function setUp(): void { parent::setUp(); Http::preventStrayRequests(); config(['app.url'=>'https://www.xn--80aesatk1az7g.kz']); }
 public function test_dry_run_does_not_save_or_mutate_source(): void { [$product,$settings]=$this->fixture();$before=$product->fresh()->only(['name','sku','category_id','price','quantity','description','primary_image']);$preview=app(OzonProductPreparationService::class)->prepare($product,$settings);self::assertDatabaseCount('ozon_products',0);self::assertEquals($before,$product->fresh()->only(array_keys($before)));self::assertSame('SKU-1',$preview->snapshot['sku']); }
 public function test_confirmation_saves_independent_snapshot_as_draft_with_warnings(): void { [$product,$settings]=$this->fixture();$service=app(OzonProductPreparationService::class);$saved=$service->save($service->prepare($product,$settings),$settings);self::assertNotNull($saved);self::assertSame(OzonProductStatus::Draft,$saved->status);self::assertSame('SKU-1',$saved->offer_id);self::assertNotEmpty($saved->prepared_payload);self::assertSame($product->name,$saved->prepared_name); }
 public function test_ready_status_is_possible_for_confirmed_local_metadata(): void { [$product,$settings]=$this->fixture();$settings['manual_taxonomy_unverified']=false;$service=app(OzonProductPreparationService::class);$prepared=$service->prepare($product,$settings);self::assertSame([], $prepared->validation->warnings);$saved=$service->save($prepared,$settings);self::assertSame(OzonProductStatus::Ready,$saved->status); }
 public function test_invalid_item_does_not_cancel_valid_batch_item(): void { [$valid,$settings]=$this->fixture();$bad=Product::query()->create(['name'=>'Bad','slug'=>'bad','category_id'=>$valid->category_id,'price'=>0,'quantity'=>1]);$rows=app(OzonProductPreparationService::class)->prepareBatch([$bad,$valid],$settings,true);self::assertNull($rows[0]['saved']);self::assertNotNull($rows[1]['saved']);self::assertDatabaseCount('ozon_products',1); }
 private function fixture(): array { $category=Category::query()->create(['name'=>'Site','slug'=>'site','status'=>'active']);$account=OzonAccount::factory()->create(['default_price_multiplier'=>1,'rounding_rule'=>'none']);$warehouse=OzonWarehouse::factory()->create(['ozon_account_id'=>$account->id,'status'=>'active']);$product=Product::query()->create(['name'=>'Product','slug'=>'product-'.uniqid(),'sku'=>'SKU-1','category_id'=>$category->id,'price'=>'100.00','quantity'=>4,'description'=>'Описание','primary_image'=>'https://www.xn--80aesatk1az7g.kz/storage/products/a.jpg']);DB::table('product_images')->insert([['product_id'=>$product->id,'path'=>'https://www.xn--80aesatk1az7g.kz/storage/products/a.jpg','role'=>'primary','is_primary'=>true,'sort_order'=>0,'created_at'=>now(),'updated_at'=>now()],['product_id'=>$product->id,'path'=>'https://www.xn--80aesatk1az7g.kz/storage/products/b.jpg','role'=>'gallery','is_primary'=>false,'sort_order'=>1,'created_at'=>now(),'updated_at'=>now()]]);ProductAttribute::query()->create(['product_id'=>$product->id,'name'=>'Объём','value'=>'100','unit'=>'мл']);return [$product,['ozon_account_id'=>$account->id,'ozon_warehouse_id'=>$warehouse->id,'description_category_id'=>'17028922','description_category_name'=>'Автохимия','type_id'=>'123','type_name'=>'Очиститель','price_multiplier'=>'1','rounding_rule'=>'none','stock_limit'=>10,'tnved_code'=>'3402','manual_taxonomy_unverified'=>true]]; }
}
