<?php

namespace App\Filament\Resources;
use App\Enums\OzonProductStatus; use App\Filament\Resources\OzonProductResource\Pages; use App\Models\OzonProduct; use App\Services\Ozon\OzonProductPreparationService; use BackedEnum; use Filament\Actions\Action; use Filament\Actions\DeleteAction; use Filament\Actions\EditAction; use Filament\Forms\Components\Select; use Filament\Forms\Components\TextInput; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Tables\Columns\ImageColumn; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Table; use Illuminate\Database\Eloquent\Builder; use UnitEnum;

class OzonProductResource extends Resource
{
 protected static ?string $model=OzonProduct::class; protected static string|BackedEnum|null $navigationIcon='heroicon-o-archive-box'; protected static string|UnitEnum|null $navigationGroup='Ozon'; protected static ?string $navigationLabel='Подготовленные товары'; protected static ?string $modelLabel='подготовленный товар'; protected static ?string $pluralModelLabel='подготовленные товары'; protected static ?int $navigationSort=20;
 public static function form(Schema $schema): Schema { return $schema->components([TextInput::make('description_category_name')->label('Категория Ozon')->required(),TextInput::make('description_category_id')->label('Category ID')->required(),TextInput::make('type_name')->label('Тип Ozon')->required(),TextInput::make('type_id')->label('Type ID')->required(),Select::make('ozon_warehouse_id')->label('Склад')->relationship('warehouse','name')->required(),TextInput::make('weight_g')->numeric()->minValue(0),TextInput::make('width_mm')->numeric()->minValue(0),TextInput::make('height_mm')->numeric()->minValue(0),TextInput::make('depth_mm')->numeric()->minValue(0),TextInput::make('tnved_code')->label('ТН ВЭД')]); }
 public static function table(Table $table): Table { return $table->emptyStateHeading('Подготовленные товары не найдены')->columns([ImageColumn::make('prepared_images.0')->label('Фото')->height(48),TextColumn::make('prepared_name')->label('Название')->searchable()->limit(45)->wrap(),TextColumn::make('offer_id')->label('SKU')->searchable(),TextColumn::make('account.name')->label('Аккаунт'),TextColumn::make('siteCategory.name')->label('Категория сайта'),TextColumn::make('description_category_name')->label('Категория Ozon'),TextColumn::make('type_name')->label('Тип'),TextColumn::make('warehouse.name')->label('Склад'),TextColumn::make('calculated_price')->label('Цена'),TextColumn::make('calculated_stock')->label('Остаток'),TextColumn::make('status')->label('Статус')->formatStateUsing(fn(OzonProductStatus $state)=>$state->label())->badge(),TextColumn::make('last_error')->label('Ошибки')->limit(30),TextColumn::make('created_at')->label('Подготовлен')->dateTime()->sortable()])->recordActions([Action::make('snapshot')->label('Snapshot')->modalHeading('Локальный snapshot')->modalContent(fn(OzonProduct $record)=>view('filament.ozon.snapshot',['record'=>$record]))->modalSubmitAction(false),EditAction::make()->label('Изменить'),DeleteAction::make()->visible(fn(OzonProduct $record)=>in_array($record->status,[OzonProductStatus::Draft,OzonProductStatus::Ready,OzonProductStatus::Failed],true))->using(fn(OzonProduct $record)=>app(OzonProductPreparationService::class)->deleteIfLocal($record))]); }
 public static function getEloquentQuery(): Builder { return parent::getEloquentQuery()->with(['product','account','siteCategory','warehouse']); }
 public static function getPages(): array { return ['index'=>Pages\ListOzonProducts::route('/'),'edit'=>Pages\EditOzonProduct::route('/{record}/edit')]; }
}
